complaint_index:
    path:     /
    defaults: { _controller: "SocialProBundle:Complaint:index" }
    methods:  GET

complaint_show:
    path:     /{id}/show
    defaults: { _controller: "SocialProBundle:Complaint:show" }
    methods:  GET

complaint_new:
    path:     /new
    defaults: { _controller: "SocialProBundle:Complaint:new" }
    methods:  [GET, POST]

complaint_edit:
    path:     /{id}/edit
    defaults: { _controller: "SocialProBundle:Complaint:edit" }
    methods:  [GET, POST]

complaint_delete:
    path:     /{id}/delete
    defaults: { _controller: "SocialProBundle:Complaint:delete" }
    methods:  DELETE
complaint_detail:
    path:     /{id}/detail
    defaults: { _controller: "SocialProBundle:Complaint:detail" }
    methods:  [GET, POST]
ajax_complaint_edit:
    path:     /
    defaults: { _controller: "SocialProBundle:Complaint:ajaxedit" }
    methods:  [GET, POST]



