events_index:
    path:     /
    defaults: { _controller: "SocialProBundle:Events:index" }
    methods:  GET

events_show:
    path:     /{id}/show
    defaults: { _controller: "SocialProBundle:Events:show" }
    methods:  [GET, POST]


events_new:
    path:     /new
    defaults: { _controller: "SocialProBundle:Events:new" }
    methods:  [GET, POST]

events_edit:
    path:     /{id}/edit
    defaults: { _controller: "SocialProBundle:Events:edit" }
    methods:  [GET, POST]

events_delete:
    path:     /{id}/delete
    defaults: { _controller: "SocialProBundle:Events:delete" }
    methods:  DELETE

events_delete_classic:
    path:     /{id}/deleteclassic
    defaults: { _controller: "SocialProBundle:Events:deleteClassic" }

events_index_suggested:
    path:     /eventsuggested
    defaults: { _controller: "SocialProBundle:Events:indexSuggested" }

