<?php

namespace SocialProBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnouncmentRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class AnnouncmentRepository extends EntityRepository
{
    public function findByKerword($keyword){
        return $this->getEntityManager()->createQuery("SELECT A FROM SocialProBundle\Entity\Announcment A 
                                                       WHERE A.keywords LIKE '%".$keyword."%' ")
                                        ->getResult();
    }

    public function countAds($keyword){
        return $this->getEntityManager()->createQuery("SELECT A FROM SocialProBundle\Entity\Announcment A 
                                                       WHERE A.keywords LIKE '%".$keyword."%' ")
            ->getResult();
    }
    public function findByCriteras($keyword, $priceMin, $priceMax, $category){
        return $this->getEntityManager()->createQuery("SELECT A FROM SocialProBundle\Entity\Announcment A 
                                                       WHERE A.keywords LIKE '%".$keyword."%' 
                                                       AND A.price BETWEEN ".$priceMin." AND ".$priceMax." 
                                                       AND A.category = ".$category)
            ->getResult();
    }
    public function orderDesc(){
        return $this->getEntityManager()
            ->createQuery("SELECT A 
                           FROM SocialProBundle\Entity\Announcment A 
                           ORDER BY A.announceId DESC ")
            ->getResult();
    }
}
